### ISSUE TITLE
Matrix Additions

### ISSUE THREAD

**Issue by harrytwright** [harrytwright/advtr-cli#3]
With the new matrix system being made, certain commands should be global, these can then generate custom matrices that are added to each build.

### Example

```yaml
matrix:
  - tag: latest
    pre_build:
      - "mkdir ./nginx/"
      - "echo '{ \"host\": \"advtr.co.uk\"}' > ./nginx/data.json"
      - "npx mustache ./nginx/data.json ./template/conf.mustache > ./nginx/default.conf"
    post_build:
      - "rm -Rf ./nginx"
  - tag: dev
    pre_build:
      - "mkdir ./nginx/"
      - "echo '{ \"host\": \"localhost\"}' > ./nginx/data.json"
      - "npx mustache ./nginx/data.json ./template/conf.mustache > ./nginx/default.conf"
    post_build:
      - "rm -Rf ./nginx"

services:
  proxy:
    name: advtr-proxy
    dockerfile: .
```

Nothing complicated, but will generate the same nginx container with a config based on if it's a dev platform and/or production

However, using the idea of a template tool, and global commands, we could make the config smaller

```yaml
before_build:
  - "mkdir ./nginx/"
  - "echo '{ \"host\": \"{{template[tag]}}]\"}' > ./nginx/data.json"
  - "npx mustache ./nginx/data.json ./template/conf.mustache > ./nginx/default.conf"

tags:
  - latest
  - dev

post_push:
  - "rm -Rf ./nginx"

services:
  proxy:
    name: advtr-proxy
    dockerfile: .
```

Ran like:

`template.json`
```json
{
  "latest": "example.co.uk",
  "dev": "localhost"
}
```

```bash
$ advtr --template template.json
```

#### Links
#2
